// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/AuthorService/author_service.proto

package AuthorService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserAsAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserAsAuthorRequest) Reset() {
	*x = RegisterUserAsAuthorRequest{}
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserAsAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserAsAuthorRequest) ProtoMessage() {}

func (x *RegisterUserAsAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserAsAuthorRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserAsAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthorService_author_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserAsAuthorRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type RegisterUserAsAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserAsAuthorResponse) Reset() {
	*x = RegisterUserAsAuthorResponse{}
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserAsAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserAsAuthorResponse) ProtoMessage() {}

func (x *RegisterUserAsAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserAsAuthorResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserAsAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthorService_author_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserAsAuthorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAuthorIdByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorIdByUserIdRequest) Reset() {
	*x = GetAuthorIdByUserIdRequest{}
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorIdByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorIdByUserIdRequest) ProtoMessage() {}

func (x *GetAuthorIdByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorIdByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorIdByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_AuthorService_author_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthorIdByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAuthorIdByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorIdByUserIdResponse) Reset() {
	*x = GetAuthorIdByUserIdResponse{}
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorIdByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorIdByUserIdResponse) ProtoMessage() {}

func (x *GetAuthorIdByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AuthorService_author_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorIdByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorIdByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_AuthorService_author_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorIdByUserIdResponse) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

var File_proto_AuthorService_author_service_proto protoreflect.FileDescriptor

var file_proto_AuthorService_author_service_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x70, 0x62, 0x22, 0x3b, 0x0a, 0x1b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x22, 0x38, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x35, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x3a, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49,
	0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x32, 0xd3,
	0x01, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x65, 0x0a, 0x14, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x12, 0x25, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x73, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x62, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x62, 0x2f, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_AuthorService_author_service_proto_rawDescOnce sync.Once
	file_proto_AuthorService_author_service_proto_rawDescData []byte
)

func file_proto_AuthorService_author_service_proto_rawDescGZIP() []byte {
	file_proto_AuthorService_author_service_proto_rawDescOnce.Do(func() {
		file_proto_AuthorService_author_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_AuthorService_author_service_proto_rawDesc), len(file_proto_AuthorService_author_service_proto_rawDesc)))
	})
	return file_proto_AuthorService_author_service_proto_rawDescData
}

var file_proto_AuthorService_author_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_AuthorService_author_service_proto_goTypes = []any{
	(*RegisterUserAsAuthorRequest)(nil),  // 0: authorpb.RegisterUserAsAuthorRequest
	(*RegisterUserAsAuthorResponse)(nil), // 1: authorpb.RegisterUserAsAuthorResponse
	(*GetAuthorIdByUserIdRequest)(nil),   // 2: authorpb.GetAuthorIdByUserIdRequest
	(*GetAuthorIdByUserIdResponse)(nil),  // 3: authorpb.GetAuthorIdByUserIdResponse
}
var file_proto_AuthorService_author_service_proto_depIdxs = []int32{
	0, // 0: authorpb.Author.RegisterUserAsAuthor:input_type -> authorpb.RegisterUserAsAuthorRequest
	2, // 1: authorpb.Author.GetAuthorIdByUserId:input_type -> authorpb.GetAuthorIdByUserIdRequest
	1, // 2: authorpb.Author.RegisterUserAsAuthor:output_type -> authorpb.RegisterUserAsAuthorResponse
	3, // 3: authorpb.Author.GetAuthorIdByUserId:output_type -> authorpb.GetAuthorIdByUserIdResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_AuthorService_author_service_proto_init() }
func file_proto_AuthorService_author_service_proto_init() {
	if File_proto_AuthorService_author_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_AuthorService_author_service_proto_rawDesc), len(file_proto_AuthorService_author_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_AuthorService_author_service_proto_goTypes,
		DependencyIndexes: file_proto_AuthorService_author_service_proto_depIdxs,
		MessageInfos:      file_proto_AuthorService_author_service_proto_msgTypes,
	}.Build()
	File_proto_AuthorService_author_service_proto = out.File
	file_proto_AuthorService_author_service_proto_goTypes = nil
	file_proto_AuthorService_author_service_proto_depIdxs = nil
}
