// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/CategoryService/category_service.proto

package CategoryService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertCategoryRequest) Reset() {
	*x = InsertCategoryRequest{}
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCategoryRequest) ProtoMessage() {}

func (x *InsertCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCategoryRequest.ProtoReflect.Descriptor instead.
func (*InsertCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_CategoryService_category_service_proto_rawDescGZIP(), []int{0}
}

func (x *InsertCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InsertCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertCategoryResponse) Reset() {
	*x = InsertCategoryResponse{}
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCategoryResponse) ProtoMessage() {}

func (x *InsertCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCategoryResponse.ProtoReflect.Descriptor instead.
func (*InsertCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_CategoryService_category_service_proto_rawDescGZIP(), []int{1}
}

func (x *InsertCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LinkBookWithCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	BookTitle     string                 `protobuf:"bytes,2,opt,name=BookTitle,proto3" json:"BookTitle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkBookWithCategoryRequest) Reset() {
	*x = LinkBookWithCategoryRequest{}
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkBookWithCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkBookWithCategoryRequest) ProtoMessage() {}

func (x *LinkBookWithCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkBookWithCategoryRequest.ProtoReflect.Descriptor instead.
func (*LinkBookWithCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_CategoryService_category_service_proto_rawDescGZIP(), []int{2}
}

func (x *LinkBookWithCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LinkBookWithCategoryRequest) GetBookTitle() string {
	if x != nil {
		return x.BookTitle
	}
	return ""
}

type LinkBookWithCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkBookWithCategoryResponse) Reset() {
	*x = LinkBookWithCategoryResponse{}
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkBookWithCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkBookWithCategoryResponse) ProtoMessage() {}

func (x *LinkBookWithCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_CategoryService_category_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkBookWithCategoryResponse.ProtoReflect.Descriptor instead.
func (*LinkBookWithCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_CategoryService_category_service_proto_rawDescGZIP(), []int{3}
}

func (x *LinkBookWithCategoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_CategoryService_category_service_proto protoreflect.FileDescriptor

var file_proto_CategoryService_category_service_proto_rawDesc = string([]byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x70, 0x62, 0x22, 0x2b, 0x0a, 0x15, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4f, 0x0a, 0x1b, 0x4c,
	0x69, 0x6e, 0x6b, 0x42, 0x6f, 0x6f, 0x6b, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x38, 0x0a, 0x1c,
	0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x6f, 0x6f, 0x6b, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xce, 0x01, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x57, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x14,
	0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x6f, 0x6f, 0x6b, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x27, 0x2e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x6f, 0x6f, 0x6b, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x42,
	0x6f, 0x6f, 0x6b, 0x57, 0x69, 0x74, 0x68, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x62, 0x2f, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_CategoryService_category_service_proto_rawDescOnce sync.Once
	file_proto_CategoryService_category_service_proto_rawDescData []byte
)

func file_proto_CategoryService_category_service_proto_rawDescGZIP() []byte {
	file_proto_CategoryService_category_service_proto_rawDescOnce.Do(func() {
		file_proto_CategoryService_category_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_CategoryService_category_service_proto_rawDesc), len(file_proto_CategoryService_category_service_proto_rawDesc)))
	})
	return file_proto_CategoryService_category_service_proto_rawDescData
}

var file_proto_CategoryService_category_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_CategoryService_category_service_proto_goTypes = []any{
	(*InsertCategoryRequest)(nil),        // 0: categorypb.InsertCategoryRequest
	(*InsertCategoryResponse)(nil),       // 1: categorypb.InsertCategoryResponse
	(*LinkBookWithCategoryRequest)(nil),  // 2: categorypb.LinkBookWithCategoryRequest
	(*LinkBookWithCategoryResponse)(nil), // 3: categorypb.LinkBookWithCategoryResponse
}
var file_proto_CategoryService_category_service_proto_depIdxs = []int32{
	0, // 0: categorypb.Category.InsertCategory:input_type -> categorypb.InsertCategoryRequest
	2, // 1: categorypb.Category.LinkBookWithCategory:input_type -> categorypb.LinkBookWithCategoryRequest
	1, // 2: categorypb.Category.InsertCategory:output_type -> categorypb.InsertCategoryResponse
	3, // 3: categorypb.Category.LinkBookWithCategory:output_type -> categorypb.LinkBookWithCategoryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_CategoryService_category_service_proto_init() }
func file_proto_CategoryService_category_service_proto_init() {
	if File_proto_CategoryService_category_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_CategoryService_category_service_proto_rawDesc), len(file_proto_CategoryService_category_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_CategoryService_category_service_proto_goTypes,
		DependencyIndexes: file_proto_CategoryService_category_service_proto_depIdxs,
		MessageInfos:      file_proto_CategoryService_category_service_proto_msgTypes,
	}.Build()
	File_proto_CategoryService_category_service_proto = out.File
	file_proto_CategoryService_category_service_proto_goTypes = nil
	file_proto_CategoryService_category_service_proto_depIdxs = nil
}
